name: Bug Report
description: バグレポート
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## 概要

  - type: input
    id: overview
    attributes:
      label: Overview
      description: 概要を書く
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: 何か問題を書く
      placeholder: 例)ボタンをクリックするとエラーが発生します
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 理想

  - type: textarea
    id: what-should-happen
    attributes:
      label: What should happen?
      description: どうなってほしいか書く
      placeholder: 例)エラーが発生しないようにしたい！！！！
    validations:
      required: true
