name: Deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1,15 * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Install, build, and upload your site output
        uses: withastro/action@v3
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy --project-name=${{ secrets.CF_PROJECT_NAME }} dist
